//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewHier
{
    using System;
    
    [Flags]
    public enum CourseTypes : int
    {
        Wpf = 1,
        CSharp = 2,
        Azure = 4,
        Java = 8,
        Sql = 16
    }
}
